//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("wniosek", Namespace="", IsNullable=false)]
public partial class Wniosek {
    
    private string jednostka_organizacyjnaField;
    
    private Kandydat kandydatField;
    
    private Zatrudnienie zatrudnienieField;
    
    private System.DateTime data_zlozeniaField;
    
    private bool data_zlozeniaFieldSpecified;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string jednostka_organizacyjna {
        get {
            return this.jednostka_organizacyjnaField;
        }
        set {
            this.jednostka_organizacyjnaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Kandydat kandydat {
        get {
            return this.kandydatField;
        }
        set {
            this.kandydatField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Zatrudnienie zatrudnienie {
        get {
            return this.zatrudnienieField;
        }
        set {
            this.zatrudnienieField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
    public System.DateTime data_zlozenia {
        get {
            return this.data_zlozeniaField;
        }
        set {
            this.data_zlozeniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool data_zlozeniaSpecified {
        get {
            return this.data_zlozeniaFieldSpecified;
        }
        set {
            this.data_zlozeniaFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Kandydat {
    
    private Dane dane_kandydataField;
    
    private Uczelnia ukonczona_uczelniaField;
    
    private Tytuly uzyskane_tytulyField;
    
    private Praca[] przebieg_pracyField;
    
    private string[] osiagnieciaField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Dane dane_kandydata {
        get {
            return this.dane_kandydataField;
        }
        set {
            this.dane_kandydataField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Uczelnia ukonczona_uczelnia {
        get {
            return this.ukonczona_uczelniaField;
        }
        set {
            this.ukonczona_uczelniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Tytuly uzyskane_tytuly {
        get {
            return this.uzyskane_tytulyField;
        }
        set {
            this.uzyskane_tytulyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("praca", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public Praca[] przebieg_pracy {
        get {
            return this.przebieg_pracyField;
        }
        set {
            this.przebieg_pracyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("osiagniecie", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public string[] osiagniecia {
        get {
            return this.osiagnieciaField;
        }
        set {
            this.osiagnieciaField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Dane {
    
    private string imieField;
    
    private string nazwiskoField;
    
    private Adres adresField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string imie {
        get {
            return this.imieField;
        }
        set {
            this.imieField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Adres adres {
        get {
            return this.adresField;
        }
        set {
            this.adresField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Adres {
    
    private string miejscowoscField;
    
    private string ulicaField;
    
    private string nr_domuField;
    
    private string nr_mieszkaniaField;
    
    private string kod_pocztowyField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string miejscowosc {
        get {
            return this.miejscowoscField;
        }
        set {
            this.miejscowoscField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nr_domu {
        get {
            return this.nr_domuField;
        }
        set {
            this.nr_domuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nr_mieszkania {
        get {
            return this.nr_mieszkaniaField;
        }
        set {
            this.nr_mieszkaniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string kod_pocztowy {
        get {
            return this.kod_pocztowyField;
        }
        set {
            this.kod_pocztowyField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Czas_Zatrudnienia {
    
    private System.DateTime do_dniaField;
    
    private bool do_dniaFieldSpecified;
    
    private bool okreslonyField;
    
    private bool okreslonyFieldSpecified;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime do_dnia {
        get {
            return this.do_dniaField;
        }
        set {
            this.do_dniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool do_dniaSpecified {
        get {
            return this.do_dniaFieldSpecified;
        }
        set {
            this.do_dniaFieldSpecified = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool okreslony {
        get {
            return this.okreslonyField;
        }
        set {
            this.okreslonyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool okreslonySpecified {
        get {
            return this.okreslonyFieldSpecified;
        }
        set {
            this.okreslonyFieldSpecified = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Zatrudnienie {
    
    private string stanowiskoField;
    
    private System.DateTime od_dniaField;
    
    private Czas_Zatrudnienia czas_zatrudnieniaField;
    
    private string wymiar_etatuField;
    
    private string podstawaField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stanowisko {
        get {
            return this.stanowiskoField;
        }
        set {
            this.stanowiskoField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
    public System.DateTime od_dnia {
        get {
            return this.od_dniaField;
        }
        set {
            this.od_dniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Czas_Zatrudnienia czas_zatrudnienia {
        get {
            return this.czas_zatrudnieniaField;
        }
        set {
            this.czas_zatrudnieniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string wymiar_etatu {
        get {
            return this.wymiar_etatuField;
        }
        set {
            this.wymiar_etatuField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string podstawa {
        get {
            return this.podstawaField;
        }
        set {
            this.podstawaField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Praca {
    
    private string rok_rozpoczeciaField;
    
    private string rok_zakonczeniaField;
    
    private string miejsceField;
    
    private string stanowiskoField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="gYear")]
    public string rok_rozpoczecia {
        get {
            return this.rok_rozpoczeciaField;
        }
        set {
            this.rok_rozpoczeciaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="gYear")]
    public string rok_zakonczenia {
        get {
            return this.rok_zakonczeniaField;
        }
        set {
            this.rok_zakonczeniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string miejsce {
        get {
            return this.miejsceField;
        }
        set {
            this.miejsceField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string stanowisko {
        get {
            return this.stanowiskoField;
        }
        set {
            this.stanowiskoField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Tytul_Naukowy {
    
    private string data_uzyskaniaField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string data_uzyskania {
        get {
            return this.data_uzyskaniaField;
        }
        set {
            this.data_uzyskaniaField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Stopien_Naukowy {
    
    private string data_uzyskaniaField;
    
    private string jakiField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string data_uzyskania {
        get {
            return this.data_uzyskaniaField;
        }
        set {
            this.data_uzyskaniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string jaki {
        get {
            return this.jakiField;
        }
        set {
            this.jakiField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Tytul_Zawodowy {
    
    private string data_uzyskaniaField;
    
    private string jakiField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string data_uzyskania {
        get {
            return this.data_uzyskaniaField;
        }
        set {
            this.data_uzyskaniaField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string jaki {
        get {
            return this.jakiField;
        }
        set {
            this.jakiField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Tytuly {
    
    private Tytul_Zawodowy tytul_zawodowyField;
    
    private Stopien_Naukowy[] stopien_naukowyField;
    
    private Tytul_Naukowy tytul_naukowyField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Tytul_Zawodowy tytul_zawodowy {
        get {
            return this.tytul_zawodowyField;
        }
        set {
            this.tytul_zawodowyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute("stopien_naukowy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Stopien_Naukowy[] stopien_naukowy {
        get {
            return this.stopien_naukowyField;
        }
        set {
            this.stopien_naukowyField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public Tytul_Naukowy tytul_naukowy {
        get {
            return this.tytul_naukowyField;
        }
        set {
            this.tytul_naukowyField = value;
        }
    }
}

/// <uwagi/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class Uczelnia {
    
    private string nazwa_uczelniField;
    
    private string nazwa_wydzialuField;
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nazwa_uczelni {
        get {
            return this.nazwa_uczelniField;
        }
        set {
            this.nazwa_uczelniField = value;
        }
    }
    
    /// <uwagi/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nazwa_wydzialu {
        get {
            return this.nazwa_wydzialuField;
        }
        set {
            this.nazwa_wydzialuField = value;
        }
    }
}
